services:
  database:
    image: mongo:latest
    container_name: voc_database
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - voc_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: voc_server
    env_file:
      - ./server/.env.development
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 5174:5174
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: voc_client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - 5173:5173
    volumes:
      - ./client:/app

volumes:
  voc_data: