services:
  database:
    image: mongo:latest
    container_name: voc_database
    command: --logpath /var/log/mongodb/mongod.log --logappend
    restart: unless-stopped
    volumes:
      - voc_data:/data/db
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  server:
    image: voc_server
    container_name: voc_server
    build:
      target: server
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./packages/server/.env
    ports:
      - 5174:5174
    healthcheck:
      test: curl --fail http://localhost:5174/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  client:
    image: voc_client
    container_name: voc_client
    build:
      target: client
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    ports:
      - 5173:80

volumes:
  voc_data: