services:
  database:
    image: mongo:latest
    container_name: voc_database
    restart: unless-stopped
    volumes:
      - voc_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: voc_server
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - ./server/.env.production
    ports:
      - 5174:5174

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: voc_client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - 5173:80

volumes:
  voc_data: