packages:
  - packages/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild

injectWorkspacePackages: true

syncInjectedDepsAfterScripts:
  - build

allowBuilds:
  '@parcel/watcher': true
  bcrypt: true
  esbuild: true
