FROM node:24-slim AS base

RUN corepack enable pnpm

WORKDIR /app

COPY --parents --exclude=node_modules **/package.json pnpm*.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile


FROM base AS server

WORKDIR /app/packages/server

RUN apt update && apt install -y curl

CMD ["pnpm", "run", "dev"]


FROM base AS client

WORKDIR /app/packages/client

CMD ["pnpm", "run", "dev"]