FROM node:24-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME/bin:$PATH"
RUN corepack enable
ENV CI=true

WORKDIR /app

COPY --parents --exclude=node_modules **/package.json pnpm*.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile


FROM base AS server

WORKDIR /app/packages/server

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
  --mount=target=/var/cache/apt,type=cache,sharing=locked \
  rm -f /etc/apt/apt.conf.d/docker-clean \
  && apt update && apt -y --no-install-recommends install curl

CMD ["pnpm", "run", "dev"]


FROM base AS client

WORKDIR /app/packages/client

CMD ["pnpm", "run", "dev"]